export const explanations = {
    // Feature Counts
    Signal: "A short peptide sequence at the N-terminus of a protein that directs the protein to a specific location in the cell, usually for secretion or membrane insertion. It is typically cleaved off after targeting.",
    Chain: "Represents the continuous sequence of amino acids forming a polypeptide chain in the protein, excluding any signal peptide or propeptide regions.",
    Transmembrane: "A region of the protein that spans across a biological membrane, typically consisting of hydrophobic amino acids that interact with the lipid bilayer.",
    Domain: "A specific region of the protein that can fold independently and often has a particular function, such as a catalytic or binding domain.",
    "Active site": "The region of the enzyme where substrate molecules bind and undergo a chemical reaction, often involving specific catalytic residues.",
    "Binding site": "A site on the protein where a ligand, ion, or substrate binds, contributing to the protein's function or regulation.",
    Site: "A specific amino acid residue annotated for a particular property or modification, such as a cleavage site, metal-binding site, or phosphorylation site.",
    Glycosylation: "A modification where a carbohydrate (sugar) group is covalently attached to an amino acid residue, typically as N-linked or O-linked glycosylation.",
    "Disulfide bond": "A covalent bond formed between the sulfur atoms of two cysteine residues, contributing to the stabilization of the protein's 3D structure.",
    "Natural variant": "A naturally occurring variation (mutation) in the protein sequence found in different individuals or populations, which may or may not affect function.",
    Mutagenesis: "A site where an amino acid has been experimentally altered (mutated) to study its role in the protein's structure or function.",
    "Sequence conflict": "A position where different sources report conflicting amino acid residues for the same position in the protein sequence.",
    Helix: "A region of the protein that forms an alpha-helix secondary structure, a common coiled shape stabilized by hydrogen bonds.",
    "Beta strand": "A region of the protein forming a beta-strand, contributing to beta-sheets in the secondary structure.",
    Turn: "A short segment of the protein that reverses the direction of the peptide chain, connecting other secondary structures like helices and strands.",
  
    // Other Information
    FUNCTION: "A general description of the biological function or role of the protein in the organism.",
    "CATALYTIC ACTIVITY": "A detailed description of the specific chemical reactions catalyzed by the protein, including substrates and products.",
    COFACTOR: "A non-protein molecule (such as a metal ion or organic compound) required for the protein's enzymatic activity.",
    "ACTIVITY REGULATION": "Information about how the protein's activity is regulated, such as activation, inhibition, or feedback mechanisms.",
    "BIOPHYSICOCHEMICAL PROPERTIES": "Physicochemical properties of the protein, including pH optimum, temperature stability, kinetic parameters, etc.",
    PATHWAY: "The biological pathway or metabolic process in which the protein participates.",
    SUBUNIT: "Information about the protein's quaternary structure, describing how it interacts with other protein chains (e.g., monomer, dimer, tetramer).",
    "SUBCELLULAR LOCATION": "The cellular compartment(s) where the protein is located, such as cytoplasm, nucleus, mitochondria, or plasma membrane.",
    MISCELLANEOUS: "Additional relevant information or notes that don't fit into other annotation categories.",
    SIMILARITY: "Notes about sequence or structural similarity between this protein and other proteins or protein families.",
    "SEQUENCE CAUTION": "A warning indicating a potential problem or uncertainty with the protein sequence, such as sequencing errors or low-quality data.",

    // Production metadata
    "Selected Group": "The current MetaMP-resolved class label after considering adjudication, expert annotations, and model-supported evidence.",
    "Group Source": "The source from which the currently resolved structural group was chosen, such as expert annotation, adjudication, or predictor-backed metadata.",
    "Selected TM Count": "The transmembrane segment count currently preferred by MetaMP for display and reconciliation.",
    "TM Source": "The source used for the currently selected transmembrane segment count.",
    "Review Status": "The current discrepancy-adjudication state for this record, such as open, reviewed, accepted, rejected, or uncertain.",
    "Replacement Strategy": "Indicates whether the current record is being interpreted through a canonical replacement entry or treated as the current record directly.",
    "Sources Present": "The databases and MetaMP-derived modules that contributed information to this record.",
    "Annotation Score Band": "A simplified confidence band derived from the UniProt annotation score.",
    "Expert vs Prediction Agreement": "Shows whether the expert structural class and MetaMP-predicted class agree for this record.",
    "Predictor Consensus": "Shows whether TMbed and DeepTMHMM agree on the transmembrane segment count.",
    "Resolved Group Label": "The reconciled structural class MetaMP currently presents for this protein.",
    "Sequence Benchmark Suitable": "Indicates whether the record is appropriate for sequence-only topology benchmarking without special caveats.",
    "State Dependent": "Flags proteins whose topology or membrane association changes across structural or functional states.",
    "Soluble to Membrane Transition": "Flags proteins known to transition from soluble to membrane-inserted states.",
    "Complex Ambiguity": "Flags records whose multi-chain or multi-entity context can complicate direct topology interpretation.",
    "Assessment Notes": "Scientific caveats and interpretation notes generated by MetaMP for this entry.",
    "OPM Regions": "Membrane-spanning regions sourced from OPM-derived topology information.",
    "TMbed Regions": "Transmembrane regions predicted by TMbed.",
    "DeepTMHMM Regions": "Transmembrane regions predicted by DeepTMHMM.",
    "Chain IDs": "Protein chain identifiers present in the associated structure context.",
    "Entity IDs": "Entity identifiers from the PDB entry container used to provide chain-aware and assembly-aware context."
  };
  
